---
- name: clone git
  ansible.builtin.yum:
    name: git
    state: present
  become: true
- name: Copy git
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir  }}"
    clone: yes
    update: yes
- name: Config lighthouse
  template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  become: true
  notify: reload-ng
